namespace TradeUnionCommittee.BLL.Enums
{
    public enum Services
    {
        Position,
        SocialActivity,
        Privileges,
        Award,
        MaterialAid,
        Hobby,
        Travel,
        Wellness,
        Tour,
        Activities,
        Cultural,
        Subdivision,
        AddressPublicHouse,

        Employee,
        PrivateHouseEmployees,
        PublicHouseEmployees,
        PositionEmployees,
        SocialActivityEmployees,
        PrivilegeEmployees,
        HobbyEmployees,
        AwardEmployees,
        MaterialAidEmployees,
        TravelEmployees,
        WellnessEmployees,
        TourEmployees,
        ActivityEmployees,
        CulturalEmployees,
        GiftEmployees,
        FluorographyEmployees,
        ApartmentAccountingEmployees,

        Family,
        TravelFamily,
        WellnessFamily,
        TourFamily,
        ActivityFamily,
        CulturalFamily,

        Children,
        HobbyChildren,
        TravelChildren,
        WellnessChildren,
        TourChildren,
        ActivityChildren,
        CulturalChildren,
        GiftChildren,

        GrandChildren,
        HobbyGrandChildren,
        TravelGrandChildren,
        TourGrandChildren,
        ActivityGrandChildren,
        CulturalGrandChildren,
        GiftGrandChildren,
    }
}