namespace TradeUnionCommittee.BLL.Enums
{
    public enum Services
    {
        Position = 3,
        SocialActivity = 4,
        Privileges = 5,
        Award = 6,
        MaterialAid = 7,
        Hobby = 8,
        Travel = 9,
        Wellness = 10,
        Tour = 11,
        Activities = 12,
        Cultural = 13,
        Subdivision = 14,
        Employee = 17,
        PrivateHouseEmployees = 18,
        PublicHouseEmployees = 19,
        AddressPublicHouse = 20,
        PositionEmployees = 21,
        SocialActivityEmployees = 22,
        PrivilegeEmployees = 23,
        HobbyEmployees = 24,
        Family = 25,
        Children = 26,
        GrandChildren = 27,
        HobbyChildrens = 28,
        HobbyGrandChildrens = 29,
        AwardEmployees = 30,
        MaterialAidEmployees = 31,
        TravelEmployees = 32,
        WellnessEmployees = 33,
        TourEmployees = 34,
        ActivityEmployees = 35,
        CulturalEmployees = 36,
        GiftEmployees = 37,
        FluorographyEmployees = 38,
        ApartmentAccountingEmployees = 39,
        TravelFamily = 40,
        WellnessFamily = 41,
        TourFamily = 42,
        ActivityFamily = 43,
        CulturalFamily = 44
    }
}