export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',

  //Auth
  AUTH_CHANGE_EMAIL_TEXT: 'AUTH_CHANGE_EMAIL_TEXT',
  AUTH_CHANGE_PASSWORD_TEXT: 'AUTH_CHANGE_PASSWORD_TEXT',
  AUTH_CHANGE_REMEMBER_ME_CHECKBOX: 'AUTH_CHANGE_REMEMBER_ME_CHECKBOX'
}

