export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',

  //Auth
  SET_CURRENT_USER: 'SET_CURRENT_USER',

  //Position
  SET_ALL_POSITIONS: 'SET_ALL_POSITIONS',
  SET_POSITION: 'SET_POSITION'
}

